// Generated by gencpp from file communicate/action.msg
// DO NOT EDIT!


#ifndef COMMUNICATE_MESSAGE_ACTION_H
#define COMMUNICATE_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communicate
{
template <class ContainerAllocator>
struct action_
{
  typedef action_<ContainerAllocator> Type;

  action_()
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
    }
  action_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::communicate::action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communicate::action_<ContainerAllocator> const> ConstPtr;

}; // struct action_

typedef ::communicate::action_<std::allocator<void> > action;

typedef boost::shared_ptr< ::communicate::action > actionPtr;
typedef boost::shared_ptr< ::communicate::action const> actionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communicate::action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communicate::action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communicate::action_<ContainerAllocator1> & lhs, const ::communicate::action_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communicate::action_<ContainerAllocator1> & lhs, const ::communicate::action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communicate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::communicate::action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communicate::action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communicate::action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communicate::action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communicate::action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communicate::action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communicate::action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57832a67d2f8a00310788a06c92c59b2";
  }

  static const char* value(const ::communicate::action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57832a67d2f8a003ULL;
  static const uint64_t static_value2 = 0x10788a06c92c59b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::communicate::action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communicate/action";
  }

  static const char* value(const ::communicate::action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communicate::action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 angle\n"
;
  }

  static const char* value(const ::communicate::action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communicate::action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communicate::action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communicate::action_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATE_MESSAGE_ACTION_H
